apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.2
    helm:
      values: |
        telemetry:
          enabled: true
          v2:
            enabled: true
            metadataExchange:
              wasmEnabled: true
            prometheus:
              wasmEnabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true