apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  project: default
  source:
    chart: kube-prometheus-stack
    targetRevision: 1.16.2
    helm:
      valueFiles:
        - $bootstrap/values/kube-prometheus-stack.yaml   
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true