apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  project: default
  source:
    chart: gateway
    targetRevision: 1.16.2
    repoURL: https://istio-release.storage.googleapis.com/charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true